### ISSUE TITLE
Get / set synonym by id

### ISSUE THREAD

**Issue by SerendipityNL** [needletail/needletail-php#3]
Currently it is not possible to retrieve or update a single synonym by using an id. The endpoint `synonym/{$id}` returns a 405. I could built the code to get it working client side, but the server needs to work with me here ;)

**Comment by GijsGoudzwaard** [comment]
Fixed in https://github.com/needletail-io/needletail-php/commit/b29fc3bb0939144bf5c629e03c2e8084fce6f203
