### ISSUE TITLE
Indexing EAN-13's throws error

### ISSUE THREAD

**Issue by SerendipityNL** [needletail/needletail-php#6]
EAN-13's are barcodes for products. They are composed of 13 integers, which is too large for the INT Needletail tries to parse the value to. Even when converted to a string before indexing them, Needletail guesses the type and converts the field to an integer field, thus throwing the same error.

> Numeric value (9976106257780) out of range of int

The first array is composed of EAN's as an integer. This just throws an error. I don't know who would store EAN's as integers, but who knows!

	$ean_ints = [
		[
			'id' => 1,
			'ean' => 9976106257780,
		],
		[
			'id' => 2,
			'ean' => 8611296545931,
		],
		[
			'id' => 3,
			'ean' => 6755316217144,
		],
		[
			'id' => 4,
			'ean' => 8772555335318,
		],
		[
			'id' => 5,
			'ean' => 1733674734077,
		],
		[
			'id' => 6,
			'ean' => 6355967267460,
		],
		[
			'id' => 7,
			'ean' => 7080432789413,
		],
		[
			'id' => 8,
			'ean' => 7162904796603,
		],
		[
			'id' => 9,
			'ean' => 8610475030635,
		],
		[
			'id' => 10,
			'ean' => 7181974485504,
		],
	];

Following the most common way to store EAN's; as a string. This would normally solve most of the problems with common databases, but Needletail does not.

	$ean_strings = [
		[
			'id' => 1,
			'ean' => '9976106257780',
		],
		[
			'id' => 2,
			'ean' => '8611296545931',
		],
		[
			'id' => 3,
			'ean' => '6755316217144',
		],
		[
			'id' => 4,
			'ean' => '8772555335318',
		],
		[
			'id' => 5,
			'ean' => '1733674734077',
		],
		[
			'id' => 6,
			'ean' => '6355967267460',
		],
		[
			'id' => 7,
			'ean' => '7080432789413',
		],
		[
			'id' => 8,
			'ean' => '7162904796603',
		],
		[
			'id' => 9,
			'ean' => '8610475030635',
		],
		[
			'id' => 10,
			'ean' => '7181974485504',
		],
	];

The last data has a nice fix, although it would suck to implement this for a large dataset. Prefix the first integer that is out of range, index all the data and update the first document with the correct EAN afterwards.

	$ean_save = [
		[
			'id' => 1,
			'ean' => 'prefix-9976106257780',
		],
		[
			'id' => 2,
			'ean' => '8611296545931',
		],
		[
			'id' => 3,
			'ean' => '6755316217144',
		],
		[
			'id' => 4,
			'ean' => '8772555335318',
		],
		[
			'id' => 5,
			'ean' => '1733674734077',
		],
		[
			'id' => 6,
			'ean' => '6355967267460',
		],
		[
			'id' => 7,
			'ean' => '7080432789413',
		],
		[
			'id' => 8,
			'ean' => '7162904796603',
		],
		[
			'id' => 9,
			'ean' => '8610475030635',
		],
		[
			'id' => 10,
			'ean' => '7181974485504',
		],
	];

**Comment by GijsGoudzwaard** [comment]
Fixed in https://github.com/needletail-io/needletail-php/commit/b29fc3bb0939144bf5c629e03c2e8084fce6f203
